-- Create test user directly via SQL (bypasses all auth API rate limits)
-- Run this in Supabase SQL Editor: Settings → SQL Editor
-- Replace values as needed.

-- First, check if user already exists
-- DO NOT run if user already exists!

-- Insert user into auth.users table directly
-- Note: This requires admin privileges. Use Supabase SQL Editor.

-- Example: Create test user with username "testuser"
-- The password hash is generated by Supabase automatically via the auth schema.

/*
DO $$
DECLARE
  v_user_id UUID;
BEGIN
  -- Check if user already exists by email
  SELECT id INTO v_user_id FROM auth.users WHERE email = 'testuser@stock-selector.local';
  
  IF v_user_id IS NULL THEN
    -- Create user via auth.create_user (server-side, no rate limit)
    SELECT auth.create_user(
      email := 'testuser@stock-selector.local',
      password := 'testpass123',
      email_confirm := true
    ) INTO v_user_id;
    
    RAISE NOTICE 'Created user with ID: %', v_user_id;
  ELSE
    RAISE NOTICE 'User already exists with ID: %', v_user_id;
  END IF;
END;
$$;
*/

-- For testing: use the Supabase dashboard → Authentication → Users → Add user
-- Or use: npx supabase auth add-user --email testuser@stock-selector.local --password testpass123
